apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: github-runner
type: Opaque


data: 
  # The value of the secret is base64 encoded
 
  # not recommended to use personal access token in pubic repositories 
  TOKEN: Z2hwXzI2SUE3V0tjTWlTVXpNOXZ0dzJ0QnhTeXY0V3BoMTF2SHZqNQ==    # echo -n "ghp_your_generated_token" | base64
